Remove reference to building mcp in as a feature
I don't believe you need to specifically compile in this feature any more.

As when I tried it complained:
```
$ cargo build --features mcp
error: the package 'groma' does not contain this feature: mcp
```